### ISSUE TITLE
Various issues following installation instructions

### ISSUE THREAD

**Issue by TomNicholas** [DragonHPC/dragon#19]
I tried to install dragon following the steps on the [Getting Started](https://dragonhpc.github.io/dragon/doc/_build/html/start/start.html#install-dragon) page of the documentation but had a few issues. I'm going to write out exactly what I did in the hopes that the installation guide can be improved.

---

> ### Pre-requisites
>
> You need to have the following software packages installed on your system:

Okay hmm - that's not a good start. I don't want to have to work out how to install all of these myself. I want any installation method to automatically install any pre-requisites. (That's why I like `conda` - it installs even non-python dependencies for python programs. See #18). Let's keep reading...

> An install script is supplied in the distribution that performs the install step(s) for you and creates and activates a virtual environment.

Oh okay cool! Well I guess that's not clear if it installs the pre-requisities or not... But let's try it anyway.

To find the `./dragon-install` script the docs say

> You will find this install script in the untarred distribution file at the root level.

This isn't super clear to me. What distribution file? How do I get that? Is that the contents of the repo? Is that the same thing as one of the two wheels already mentioned? If this is just a text file why don't you just tell me where in the repo it is?

So instead I searched for `dragon-install`, found [the file](https://github.com/DragonHPC/dragon/blob/c608fba8591b0e6bd01d750afe1713c79668c6ea/src/bin/dragon-install) in the repo, cloned the repo, and tried to run that script from the top-level directory of the cloned repo using `./src/bin/dragon-install`. (This is on my local machine - a Mac.) I got this output:

```
(numpy2.0_released) tom@Toms-MacBook-Pro dragon % ./src/bin/dragon-install 
ls: /Users/tom/Documents/Work/Code/dragon/src/bin/pycapnp*.whl: No such file or directory
ls: /Users/tom/Documents/Work/Code/dragon/src/bin/dragon*.whl: No such file or directory
Pycapnp wheel is
ERROR: You must give at least one requirement to install (see "pip help install")

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
ERROR: You must give at least one requirement to install (see "pip help install")

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
./src/bin/dragon-install: line 18: module: command not found
./src/bin/dragon-install: line 19: module: command not found
```

Noticing that I was already inside a conda environment when I ran that, I tried deactivating that environment and running the script again, getting a different error:

```
tom@Toms-MacBook-Pro dragon % ./src/bin/dragon-install
ls: /Users/tom/Documents/Work/Code/dragon/src/bin/pycapnp*.whl: No such file or directory
ls: /Users/tom/Documents/Work/Code/dragon/src/bin/dragon*.whl: No such file or directory
Pycapnp wheel is
ERROR: You must give at least one requirement to install (see "pip help install")
ERROR: You must give at least one requirement to install (see "pip help install")
./src/bin/dragon-install: line 18: module: command not found
./src/bin/dragon-install: line 19: module: command not found
```

Oh wait! There's something about "if there was an error loading modules". So let's look at "Enabling Module Support". It says 

> If you intend to use Dragon on your own Linux VM or an image that you personally installed

Hmmm - I'm on a Mac. Do either of those apply to me? 

> or other login script

I guess Macs have the `~/.zshrc`... Let's try adding this line to that. The command itself is

> `source /usr/share/modules/init/bash`
> 
> If you use a different shell, look in the `init` directory for a script for your shell.

Okay I am using a different shell - where am I looking for the `init` directory... It seems on this machine I have a `/usr/share/` directory, but it doesn't contain a `modules` directory. 😕 I'm not sure where else to look, but I know I need a `module` command, now I guess I'll ask ChatGPT how I can get a `module` command on MacOS 🤷‍♂️ 

ChatGPT says I can install the Environment Modules package using `brew install modules`. That seems reasonable, let's try that... Okay that installed something, and said at the end

```
To activate modules, add the following at the end of your .zshrc:

  source /opt/homebrew/opt/modules/init/zsh

You will also need to restart your terminal for this change to take effect.
```

That seems promising! Hopefully we're back on track! Let's add that line to `.zshrc`, restart the terminal, and try running `./src/bin/dragon-install` again.

```
tom@Toms-MBP dragon % ./src/bin/dragon-install
ls: /Users/tom/Documents/Work/Code/dragon/src/bin/pycapnp*.whl: No such file or directory
ls: /Users/tom/Documents/Work/Code/dragon/src/bin/dragon*.whl: No such file or directory
Pycapnp wheel is
ERROR: You must give at least one requirement to install (see "pip help install")
ERROR: You must give at least one requirement to install (see "pip help install")
./src/bin/dragon-install: line 18: module: command not found
./src/bin/dragon-install: line 19: module: command not found
```

Okay that didn't work at all. I now notice the `.whl: No such file or directory` - perhaps I should have started with that? But it's not clear where I actually get those `.whl` files. My understanding is that wheels are what normally get uploaded to [PyPI](https://pypi.org/), but I don't see anything about using `pip install dragon` or similar in the Getting Started docs.

Also it still seems weird that it still says `module: command not found`, even though I am now able to use the `module` command and see a man page. I'm stopping here for now.

EDIT: Now I see that the ReadMe says that Dragon is not supported on MacOS! 🤦‍♂️ That's kind of annoying for development purposes. But I guess when I come back to this I will try the same steps on a HPC machine instead.

---

I'm sorry if this seems pedantic, but if we want people to use Dragon it should be as trivial to install and get up and running as possible. I personally wanted to use Dragon to do local development, towards a [HPC Executor for Cubed](https://github.com/cubed-dev/cubed/issues/467#issuecomment-2226879622). If I'm getting stuck then users who aren't developers will definitely get stuck!

P.S. Ideally this would be as simple as `conda install -c conda-forge dragon` ! (see #18)

**Comment by TomNicholas** [comment]
Okay attempt 2. Let's try the container approach to running locally.

> If you have not used containers before, download Docker and Visual Studio Code (VSCode) to your laptop, start Docker, and open the Dragon repository in VSCode.

Okay I already use VSCode, but I don't have Docker, so I downloaded Docker Desktop. Then I opened the cloned dragon repo inside VSCode, and did see the docker prompts! Following those, it seemed to mostly work until the last step, which output in the VSCode terminal

```
Running the postStartCommand from devcontainer.json...

[1082253 ms] Start: Run in container:
fatal: not in a git directory
[1082309 ms] postStartCommand failed with exit code 128. Skipping any further user-provided commands.
Done. Press any key to close the terminal.
```

Hmm. The wording of the next part is a bit unclear:


> Open a terminal pane in VSCode and type the following from the root directory of the container.
>
> Whether in a container or not, once you have a terminal window, navigate to the root directory of the repository and type the following.
>
> ```
> . hack/clean_build
> ```

Is there some other command missing between the first and second lines? Again I asked ChatGPT, which told me to run 
`docker build -t <my-image-name> .`, 
then 
`docker run -d -p 3000:3000 --name <my-container-name> <your-image-name>`.

Apparently I can choose the image name so I chose `dragon`, then for the container name I'm not sure, so I looked it up with `docker ps -a`. Apparently the one I built is called `sleepy_newton`??

```
(base) tom@Toms-MBP .devcontainer % docker run -d -p 3000:3000 --name sleepy_newton dragon         

docker: Error response from daemon: Conflict. The container name "/sleepy_newton" is already in use by container "9106b1921e49b2eedc5027a9666bad194816ec699f9dfcf48853e43d38387674". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```

Okay maybe not... Let's just try 
```
(base) tom@Toms-MBP .devcontainer % docker run -d -p 3000:3000 --name dragon_container dragon

04f35dcbce7057fddfa0add0a1228d96878ecbd0d9c0ca8b8ceefb7c4e517ef4
```
That seems okay... But apparently that exited as soon as I opened it?
```
(base) tom@Toms-MBP .devcontainer % docker ps -a
CONTAINER ID   IMAGE                                                                         COMMAND                  CREATED              STATUS                          PORTS      NAMES
04f35dcbce70   dragon                                                                        "/bin/bash"              About a minute ago   Exited (0) About a minute ago              dragon_container
9106b1921e49   vsc-dragon-70d571feab709d6927f5cf384d5bc87e096bc19eb9f3abb306c95eb081501591   "/bin/sh -c 'echo Co…"   23 minutes ago       Up 23 minutes                   8888/tcp   sleepy_newton
c882740cb2c6   docker/welcome-to-docker:latest                                               "/docker-entrypoint.…"   47 minutes ago       Exited (0) 46 minutes ago                  welcome-to-docker
```

Okay ChatGPT says I need to run the container interactively, so I tried `(base) tom@Toms-MBP .devcontainer % docker run -it dragon /bin/sh` That seems to give me a shell

```
# ls
bin  boot  dev	etc  home  lib	media  mnt  opt  proc  root  run  sbin	srv  sys  tmp  usr  var
```
but then I need to navigate to the root directory of the dragon repository, which I'm not sure is anywhere in here... Indeed `# find / -type d -name "dragon"` returns nothing. Okay I'm stuck, so I'm going to give up on the container approach for now.

**Comment by TomNicholas** [comment]
Okay 3rd attempt - I've logged into NERSC so I'm now actually on a linux system. I've never actually used this particular HPC system before, so I start by downloading miniconda and making a dedicated conda environment. Then I clone the dragon repo, and run `. hack/clean_build`.

This does a huge amount of uninstalling and re-installing of things, presumably overwriting a lot of my conda environment. But it does appear to be compiling something!

Okay that seems to have worked! On to the `hello_world` example.

```
(_env) (dragon) tnichola@perlmutter:login24:~/Code/experiments/dragon> python hello_world.py 
  File "/global/u1/t/tnichola/Code/experiments/dragon/hello_world.py", line 1
    import dragon
IndentationError: unexpected indent
```

Looks like the code block in the readme has incorrect indentation for python, which I have to fix manually...

Now I tried running the `hello_world` multiple ways:

```
(_env) (dragon) tnichola@perlmutter:login24:~/Code/experiments/dragon> python hello_world.py 
Traceback (most recent call last):
  File "/global/u1/t/tnichola/Code/experiments/dragon/hello_world.py", line 16, in <module>
    mp.set_start_method("dragon")
  File "/opt/cray/pe/python/3.11.5/lib/python3.11/multiprocessing/context.py", line 251, in set_start_method
    self._actual_context = self.get_context(method)
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/cray/pe/python/3.11.5/lib/python3.11/multiprocessing/context.py", line 243, in get_context
    return super().get_context(method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/cray/pe/python/3.11.5/lib/python3.11/multiprocessing/context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'dragon'
```
I would have though that should have worked, that's not good.

But the readme does say

> run it by executing dragon hello_world.py.

I'm not sure if that's an actual code command I'm supposed to execute (e.g. `dragon hello_world.py`) - that would be weird if I can only execute python programs using a special `dragon` command...

```
(_env) (dragon) tnichola@perlmutter:login24:~/Code/experiments/dragon> dragon hello_world.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/global/homes/t/tnichola/Code/dragon/src/dragon/cli/__main__.py", line 46, in <module>
    main()
  File "/global/homes/t/tnichola/Code/dragon/src/dragon/cli/__main__.py", line 42, in main
    _main()
  File "/global/homes/t/tnichola/Code/dragon/src/dragon/launcher/launch_selector.py", line 159, in main
    dl = get_launcher()
         ^^^^^^^^^^^^^^
  File "/global/homes/t/tnichola/Code/dragon/src/dragon/launcher/launch_selector.py", line 85, in get_launcher
    multi_mode = determine_environment()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/homes/t/tnichola/Code/dragon/src/dragon/launcher/launch_selector.py", line 77, in determine_environment
    raise RuntimeError(msg)
RuntimeError: Executing in a Slurm environment, but with no job allocation.
    Resubmit as part of an 'salloc' or 'sbatch' execution
```

Okay that looks like it did actually enter python and try to run, but wasn't set up to run as an interactive job properly maybe? Perhaps the point of the `dragon` command is to launch things interactively using SLURM? It's unclear from the readme - the next section on Multi-Node Dragon mentions something that sounds related, but it also implies that the previous attempt should have worked.

Let's try following the link in 

> For more details see [Running Dragon on a Multi-Node System](https://dragonhpc.org/).

Oh wait that just takes me to the homepage of the docs. But if I try the same link on the page further down I get to somewhere new. Oh wait there are more detailed instruction on [this page](https://dragonhpc.github.io/dragon/doc/_build/html/uguide/running_dragon.html#running-dragon)! So there are two sections on Running Dragon, one in Getting Started and one in Users Guide, with slightly different content.

Okay so I can do `module load dragon`, and I see there is an option to force it to run on a single node... I'm on a login node, and I haven't configured anything about SLURM on my account yet, so maybe let's try that?

```
...
Hello World from 1672563 with payload=253 
Hello World from 1672585 with payload=254
Hello World from 1672587 with payload=255 
+++ head proc exited, code 0
```

Success!!

**Comment by kentdlee** [comment]
> I tried to install dragon following the steps on the [Getting Started](https://dragonhpc.github.io/dragon/doc/_build/html/start/start.html#install-dragon) page of the documentation but had a few issues. I'm going to write out exactly what I did in the hopes that the installation guide can be improved.
> 
> > ### Pre-requisites
> > You need to have the following software packages installed on your system:
> 
> Okay hmm - that's not a good start. I don't want to have to work out how to install all of these myself. I want any installation method to automatically install any pre-requisites. (That's why I like `conda` - it installs even non-python dependencies for python programs. See #18). Let's keep reading...

Seems like maybe you figured out that the list below this (omitted) was a list including Python and GCC. We'll add to this that you can run "single node" if you like to try things out on a smaller system. I have made note of that. 

> 
> > An install script is supplied in the distribution that performs the install step(s) for you and creates and activates a virtual environment.
> 
> Oh okay cool! Well I guess that's not clear if it installs the pre-requisities or not... But let's try it anyway.

Hopefully you figured out that Python was listed as a pre-req for a reason. But I made note that we are not clear on our "getting started by building Dragon" and "getting started by using a pre-built binary". We'll get that updated in next release.

> 
> To find the `./dragon-install` script the docs say
> 
> > You will find this install script in the untarred distribution file at the root level.
> 
> This isn't super clear to me. What distribution file? How do I get that? Is that the contents of the repo? Is that the same thing as one of the two wheels already mentioned? If this is just a text file why don't you just tell me where in the repo it is?
> 
> So instead I searched for `dragon-install`, found [the file](https://github.com/DragonHPC/dragon/blob/c608fba8591b0e6bd01d750afe1713c79668c6ea/src/bin/dragon-install) in the repo, cloned the repo, and tried to run that script from the top-level directory of the cloned repo using `./src/bin/dragon-install`. (This is on my local machine - a Mac.) I got this output:
> 
> ```
> (numpy2.0_released) tom@Toms-MacBook-Pro dragon % ./src/bin/dragon-install 
> ls: /Users/tom/Documents/Work/Code/dragon/src/bin/pycapnp*.whl: No such file or directory
> ls: /Users/tom/Documents/Work/Code/dragon/src/bin/dragon*.whl: No such file or directory
> Pycapnp wheel is
> ERROR: You must give at least one requirement to install (see "pip help install")
> 
Right, the dragon-install is for a pre-built binary. 

> [notice] A new release of pip is available: 24.0 -> 24.2
> [notice] To update, run: pip install --upgrade pip
> ERROR: You must give at least one requirement to install (see "pip help install")
> 
> [notice] A new release of pip is available: 24.0 -> 24.2
> [notice] To update, run: pip install --upgrade pip
> ./src/bin/dragon-install: line 18: module: command not found
> ./src/bin/dragon-install: line 19: module: command not found
> ```
> 
> Noticing that I was already inside a conda environment when I ran that, I tried deactivating that environment and running the script again, getting a different error:
> 
> ```
> tom@Toms-MacBook-Pro dragon % ./src/bin/dragon-install
> ls: /Users/tom/Documents/Work/Code/dragon/src/bin/pycapnp*.whl: No such file or directory
> ls: /Users/tom/Documents/Work/Code/dragon/src/bin/dragon*.whl: No such file or directory
> Pycapnp wheel is
> ERROR: You must give at least one requirement to install (see "pip help install")
> ERROR: You must give at least one requirement to install (see "pip help install")
> ./src/bin/dragon-install: line 18: module: command not found
> ./src/bin/dragon-install: line 19: module: command not found
> ```
> 
> Oh wait! There's something about "if there was an error loading modules". So let's look at "Enabling Module Support". It says
> 
> > If you intend to use Dragon on your own Linux VM or an image that you personally installed
> 
> Hmmm - I'm on a Mac. Do either of those apply to me?
> 
> > or other login script
> 
> I guess Macs have the `~/.zshrc`... Let's try adding this line to that. The command itself is
> 
> > `source /usr/share/modules/init/bash`
> > If you use a different shell, look in the `init` directory for a script for your shell.
> 
> Okay I am using a different shell - where am I looking for the `init` directory... It seems on this machine I have a `/usr/share/` directory, but it doesn't contain a `modules` directory. 😕 I'm not sure where else to look, but I know I need a `module` command, now I guess I'll ask ChatGPT how I can get a `module` command on MacOS 🤷‍♂️
> 
> ChatGPT says I can install the Environment Modules package using `brew install modules`. That seems reasonable, let's try that... Okay that installed something, and said at the end
> 
> ```
> To activate modules, add the following at the end of your .zshrc:
> 
>   source /opt/homebrew/opt/modules/init/zsh
> 
> You will also need to restart your terminal for this change to take effect.
> ```
> 
> That seems promising! Hopefully we're back on track! Let's add that line to `.zshrc`, restart the terminal, and try running `./src/bin/dragon-install` again.
> 
> ```
> tom@Toms-MBP dragon % ./src/bin/dragon-install
> ls: /Users/tom/Documents/Work/Code/dragon/src/bin/pycapnp*.whl: No such file or directory
> ls: /Users/tom/Documents/Work/Code/dragon/src/bin/dragon*.whl: No such file or directory
> Pycapnp wheel is
> ERROR: You must give at least one requirement to install (see "pip help install")
> ERROR: You must give at least one requirement to install (see "pip help install")
> ./src/bin/dragon-install: line 18: module: command not found
> ./src/bin/dragon-install: line 19: module: command not found
> ```
> 
> Okay that didn't work at all. I now notice the `.whl: No such file or directory` - perhaps I should have started with that? But it's not clear where I actually get those `.whl` files. My understanding is that wheels are what normally get uploaded to [PyPI](https://pypi.org/), but I don't see anything about using `pip install dragon` or similar in the Getting Started docs.
> 
> Also it still seems weird that it still says `module: command not found`, even though I am now able to use the `module` command and see a man page. I'm stopping here for now.
> 
> EDIT: Now I see that the ReadMe says that Dragon is not supported on MacOS! 🤦‍♂️ That's kind of annoying for development purposes. But I guess when I come back to this I will try the same steps on a HPC machine instead.
> 
> I'm sorry if this seems pedantic, but if we want people to use Dragon it should be as trivial to install and get up and running as possible. I personally wanted to use Dragon to do local development, towards a [HPC Executor for Cubed](https://github.com/cubed-dev/cubed/issues/467#issuecomment-2226879622). If I'm getting stuck then users who aren't developers will definitely get stuck!
> 
> P.S. Ideally this would be as simple as `conda install -c conda-forge dragon` ! (see #18)

Thanks for the feedback. We are working on making it pip installable and that is coming. In the meantime it seems like maybe you might benefit from building from scratch. If you have cloned the repo, in the root directory you can type

. hack/clean_build 

and that will build it. You should run this from a container on your Mac as Dragon is not natively supported on a Mac. 

After building it, you can run it single node in the container. Choose any of the example programs or something else and run it with 

dragon my_prog.py 

where my_prog.py is a Python multiprocessing program which imports dragon and sets the start method. See our example programs (under subdirtories of examples/) if you would like a sample to follow. 

We'll get the other documentation updated and make the install of pre-built binary files easier in the near future! Thanks for the feedback.

**Comment by kentdlee** [comment]
Tom, thanks for your input and flow of consciousness on this. It helps in understanding where our users are coming from. 

We'll get updates out there for the "Getting Started" documentation in the next release (0.11 likely) which is coming sometime this fall. In the meantime, it seems that there may be a few things I can clear up. Happy to continue this way if you like. Just let us know. 

In the meantime you can either install a pre-built binary or you can build from scratch. Building is not too hard. Looks like you were pretty close. In VS Code you can re-open in a Container. It appears that for some reason your container did not build correctly on your laptop. You can try it again to see if it completes, but the container should build automatically and you should not get a "post processing" error. You might need to talk to someone about the container not starting correctly for you. 

One issue I have seen is if ZScaler is running it will create problems for building containers because it too agressively blocks websites that are used in building containers. I have to turn off ZScaler on my laptop with "sudo sudo launchctl unload /Library/LaunchDaemons/com.zscaler.service.plist && sudo launchctl unload /Library/LaunchDaemons/com.zscaler.tunnel.plist". That command will shut ZScaler down until you reboot. 

If you have ZScaler running, then shut it down and try opening the repo in VS Code again and it will again restart in a container if you allow it. That might fix that step up for you.

Then in a terminal window inside VS Code (Go To Terminal to open a new one if you don't have one) and type

. hack/clean_build 

from the root dir of the repo. That will build all of dragon in the container and you can run examples single node on your 
laptop.

The dragon run-time includes a "run-time" as the name implies so you use the "dragon" command to start the run-time and then run a python program within it". You can also run arbitrary binary files as well, but that would entail using lower level Dragon components. I am guessing you want to use it to run some Python code. In that case "dragon my_prog.py" will do that for you.

Inside your "my_prog.py" file you would need to import dragon and set "dragon" as the start method. 

Hopefully that helps, but thanks for the input on your experience. We'll get updates made to that asap.

**Comment by kentdlee** [comment]
I'll add that we'll leave the issue open for now and close it once we have made the changes and are ready to publish them.

**Comment by kentdlee** [comment]
In the meantime, if the response above does not answer something for you, please reach out. One of my teammates should be able to help you over the next couple of weeks. Thanks again!
